### ISSUE TITLE
Feat : 10월 9일 이후 작업 todo list

### ISSUE THREAD

**Issue by dusunax** [dusunax/game#1]
## 개요

- 10월 9일까지 항해톤(1회) 심사 기간이므로, 현재 프로젝트를 추가 작업하지 않습니다.
- 심사 기간 이후, 주말에 아래 체크리스트 항목을 진행합니다.(아마도 14~15일)

## Todo List 
- [ ] 기능 추가A: 점수 기록 (score + nickname) Firebase 연결
- [ ] 기능 추가B: Google Analytics 추가
- [ ] 기능 추가C: 게임 도중에 초기화 버튼
- [ ] 기능 추가D: 게임 오버 시, 재시작 버튼
- [ ] 기능 추가E: 게임 오버, 게임 클리어 시 Lottie 애니메이션 추가 etc) confetti
- [ ] 기능 추가F: 게임 sound 추가
- [ ] 버그 수정A: 게임 종료 타이밍 관련 버그 수정
- [ ] 버그 수정B: MouseConstranit 타겟 제한
- [ ] 버그 수정C: stage 4에서 송편 가끔 굴러 떨어짐
- [ ] 버그 수정D: 가끔 송편이 사라짐 < ? 재현 필요

### 현재 socre 데이터_231005

- 집계 방식: 카카오톡 스크린샷 인증
- 심사(10월 9일) 이후 DB 추가 예정

| score | name | 등수 (상품) |
| --- | --- | --- |
| 5180 | DSA |  |
| 5060 | KJB |  |
| 4955 | KJB | 10/4 유저테스트 1등 (☕️) |
| 4925 | HSM |  |
| 4850 | YCS |  |
| 4745 | KHJ | 선착순 1등 (☕️) |
| 4580 | CRH |  |
| 4580 | LMS |  |
